server:
  port: 8000

spring:
  application:
    name: openknot-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            # WebFlux 핸들러에도 CORS 매핑 붙이려면 true 권장
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "https://app.winter-cloud.com"  # 실제 프론트 도메인
                  # - "http://localhost:3100"       # 로컬 개발용으로 필요하면 추가
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"        # Authorization, Content-Type 등 전부 허용
                exposed-headers: "*"        # 클라이언트에서 읽을 수 있는 헤더
                allow-credentials: true     # 쿠키/Authorization 헤더 허용
                max-age: 3600               # preflight 캐시(초)


jwt:
  secret: ${JWT_SECRET}